In [1]:
import requests
from pandas.io.json import json_normalize
import csv
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
url_list = ["1_1",
            "1_2",
            "1_3",
            "1_4",
            "1_8",
            "1_26",
            "1_49"
           ]

feature_list= ["102",#total_points
        ]

feature_name = ["total_points", 
                "successful_raids",
                "raid_points",
                "successful_tackles",
                "tackle_points"             ]
url = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/{}_{}_stats.json"



#.format("1_49_96")

In [4]:
def create_df(feature_name,feature_list):
    for i in range(0,len(url_list)):
        temp = pd.DataFrame()
        url_s = url.format(url_list[i],feature_list)
        jsonData = requests.get(url_s).json()
        temp = json_normalize(jsonData['data'])
        temp.rename(columns = {'value':feature_name}, inplace = True)
        temp.rename(columns = {'rank':feature_name+"_rank"}, inplace = True)
        temp.rename(columns = {'match_played':feature_name+"_match_played"}, inplace = True)
        temp['season'] = i+1
        if i==0:
            final =temp
        else:
            final=final.append(temp)
    return final

In [5]:
total_points_df = create_df(feature_name[0],feature_list[0])

D:\Anaconda\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [6]:
total_points_df['player_id'].unique()

array([  29,   81,  143,   26,   58,   69,  118,  142,   52,  124,   92,
         75,   88,   86,   41,  111,   94,  105,  146,   66,   12,   55,
         42,  141,  107,   51,   85,  156,   70,   96,   71,  150,  160,
         73,  147,   56,   67,   28,  157,  162,  168,  108,   98,   20,
         45,  152,  161,  163,  174,   79,  123,  165,  166,   84,   89,
         72,   44,   54,   16,   46,   76,  167,  159,  164,  169,   32,
         10,  170,  173,    4,   36,   53,   19,   61,   38,   21,   13,
         80,   68,   97,  151,  155,  158,  154,  113,   14,   23,   77,
         87,  144,  145,    5,    9,   11,   17,  148,  248,  217,  252,
        211,  190,  251,  240,  109,   34,  194,  171,  212,  207,  204,
        182,  243,  242,  238,  264,  245,  180,  195,  185,  233,  231,
        181,  261,  259,  191,  232,  235,  222,  268,  197,  179,  234,
        267,  246,  244,  249,  219,  178,  184,  202,  208,  260,  236,
        223,  250,  225,  241,  205,  206,  221,  224,  237,  199,  200,
        201,  239,  326,  320,  119,  318,  322,  290,  309,  314,  311,
        272,  277,  275,  215,  172,  288,  293,  106,  285,  278,  313,
        283,  299,  308,  324,  316,  263,  227,  193,  296,  317,  315,
        307,  312,  388,  389,  300,  387,  391,  386,  360,  363,  376,
        358,  380,  347,  357,  366,  370,  371,  390,  210,  301,  367,
        368,  364,  373,  757,  791,  579,  489,  745,  733,  769,  795,
        764,  567,  725,  724,  361,  686,  718,  762,  576,  611,  522,
        722,  482,  773,  734,  372,  648,  728,  771,  796,  365,  536,
        613,  665,  667,  696,  784,  772,  676,  837,  637,  121,  101,
        710,  735,  736,  661,  689,  694,  732,  605,  218,  578,  738,
        768,  741,  751,  730,  746,  776,  790,  792,  640,  647,  660,
        690,  712,  519,  392,  266,  279,  726,  774,  765,  384,  513,
        705,  580, 2026, 2296,  763, 2357, 2475, 2028, 2023,  778, 2462,
        794, 2476,  621, 2463, 2316, 2481, 2307, 2298, 2274, 2470,  786,
        274, 2479,  731,  644, 2278, 2290, 2291, 2325, 2306, 2266, 2257,
       2336, 2315, 2020,  608, 2314, 2328, 2353, 2024,  599,  214, 2021,
       2262, 2302, 2471, 2335, 2313,  793,  698,  708,   74, 2318, 2351,
       2482, 2661, 2488,  484, 2508, 2330, 2286, 2485, 2670,  115,  571,
       2492, 2657,  684, 2503, 2498, 2682, 2502, 2486, 2672, 2512, 2667,
       2660, 2494, 2496, 2659, 2376, 2322,  481, 2506, 2321, 2514, 2662,
       2666, 2507, 2504, 2665, 2474, 2478, 2493, 2644, 2669, 2683, 2041,
       2282,  509, 2489, 2025, 2671, 2668, 2515, 2501], dtype=int64)

In [7]:
player_lst = [  29,   81,  143,   26,   58,   69,  142,   52,  124,   92, 75,   88,   86,   41,  111,   94,  105,  146,   66,   12,
         42,  141,  107,   51,   85,  156,   70,   96,   71,  150,  160, 73,  67,   28,  157,  162, 20,
         152,  161,  163,  174,   123,  165,  84,  72,   44,   54,   16,   46,   167, 164, 
         170,  173,    36,   53,   61, 21,   13,  97,  155,  158,  14,  
        87,  9,   11, 217,  252, 211,  190,  251,  240,  109,   34,  194, 212,  207,  204,
       242, 264,  245,  195,  185,  233,  231, 261,  259,  191,  232, 268,  197,  179,  234,
       249,  219, 202, 250,  200,
        201,  326,  320,  119,  318,  322,  290, 311, 272,  275,  215,  172,  288,  293,  106,313,
        299,   324, 388,  389,  300,  387, 386,  360,  363,  376,
        358,  347,  357,  366,  370,  371,  390,  301,  368,757,  791,  579,  489,  745,  733,  769,  795,
        764,  567,  725,  724,  361,  686,  718,  762,  576,  611,  522, 722,  482,  773,  734,  372,  648,  728,  771,  796,  365,  536,
        613,  665,  667,  696,  784,  772,  676,  837,  637,  121,  101, 710,  735,  736,  661,  689,  694,  732,  605,  218,  578,  738,
        768,  741,  751,  730,  746,  776,  790,  792,  640,  647,  660, 690,  712,  519,  392,  266,  279,  726,  774,  765,  384,  513,
        705,  580, 2026, 2296,  763, 2357, 2475, 2028, 2023,  778, 2462, 794, 2476,  621, 2463, 2316, 2481, 2307, 2298, 2274, 2470,  786,
        274, 2479,  731,  644, 2278, 2290, 2291, 2325, 2306, 2266, 2257, 2336, 2315, 2020,  608, 2314, 2328, 2353, 2024,  599,  214, 2021,
       2262, 2302, 2471, 2335, 2313,  793,  698,  708,   74, 2318, 2351, 2482, 2661,  484, 2508, 2488, 2330, 2286, 2670,  115,  571, 2485,
        684, 2657, 2492, 2503, 2498, 2486, 2502, 2672, 2512, 2667, 2682, 2494, 2496, 2659, 2660, 2322,  481, 2321, 2662, 2506, 2514, 2504,
       2507, 2665, 2666, 2478, 2644, 2683, 2669, 2474, 2041,  509, 2025, 2489, 2501, 2376, 2671, 2515]

In [8]:
def player_data():
    try:
        for i in range(0,len(player_lst)):
            temp = pd.DataFrame()
            url_s = url.format(player_lst[i],'player')
            jsonData = requests.get(url_s).json()
            temp = json_normalize(jsonData['over_all_stats'])
            if i==0:
                final =temp
            else:
                final=final.append(temp)
        return final
    except:
        pass

In [9]:
url = "https://www.prokabaddi.com/sifeeds/kabaddi/static/json/{}_{}.json"
player_stats=player_data()

In [10]:
player_stats.head()

   career_best_points  defence_touch_points  defending_bonus_points  empty_raid  green_cards high_5s location  match_played        name  not_out_percentage  player_id  player_team                                    player_team_arr  point  points_defence_offence  points_per_match_raid_tackle  raid_bonus_points raid_map_locations  raid_points_per_match  raid_touch_points  raids  red_cards role  series_id                        series_name  success_raid_percent  success_raids  success_tackles  success_tackles_per_match super_10s  super_raids  super_tackles tackle_bonus_points  tackle_success_rate  tackles total_capture_points  total_defending_points  total_raid_points  total_tackle_points  unsuccesful_tackles  unsuccess_raids  yellow_cards
0                  16                    14                       2          86            3       0                     16  Anup Kumar               81.96         29            0  [{'team_id': 5, 'team_name': 'U Mumba', 'team_...    169                     169                         10.56                 40                                      9.68                115    255          0               1  Pro Kabaddi League Season 1, 2014                 60.78            123               12                       0.75        10            8              2                                    40.00       35                                           14                155                   14                   23               46             0
1                  10                     7                       1         148            8       0                     14  Anup Kumar               85.65         29            0  [{'team_id': 5, 'team_name': 'U Mumba', 'team_...     81                      81                          5.78                  7                                      5.28                 67    244          0               2  Pro Kabaddi League Season 2, 2015                 30.32             61                6                       0.42         1            1              1                                    58.33       12                                            7                 74                    7                    6               35             0
2                   9                     3                       0         121            1       0                     13  Anup Kumar               88.03         29            0  [{'team_id': 5, 'team_name': 'U Mumba', 'team_...     79                      79                          6.07                 11                                      5.84                 65    209          0               3  Pro Kabaddi League Season 3, 2016                 36.36             63                3                       0.23         0            3              0                                    33.33        9                                            3                 76                    3                    6               25             1
3                  11                    10                       1         141            4       0                     14  Anup Kumar               87.39         29            0  [{'team_id': 5, 'team_name': 'U Mumba', 'team_...     82                      82                          5.85                 19                                      5.14                 53    230          0               4  Pro Kabaddi League Season 4, 2016                 31.30             60                9                       0.64         0            1              1                                    41.66       24                                           10                 72                   10                   15               29             1
4                  11                    23                       4         153            6       0                     21  Anup Kumar               84.34         29            0  [{'team_id': 5, 'team_name': 'U Mumba', 'team_...    135                     135                          6.42                 42                                      5.33                 70    281          0               8  Pro Kabaddi League Season 5, 2017                 39.85             84               19                       0.90         2            2              4                                    38.33       60                                           23                112                   23                   41               44             0

In [11]:
file_name = "Player_stats_info.csv"
player_stats.to_csv(file_name, sep=',',index=False)